name: Build Docker images

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build API Docker image
        run: |
          docker build -t andyzetter/api:latest api

      - name: Run API tests
        run: |
          docker run --rm andyzetter/api:latest npm test
      

    
  build-second-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build Return2 Docker image
        run: |
          docker build -t andyzetter/return2:latest return2

      - name: Run return2 tests
        run: |
          docker run --rm andyzetter/return2:latest npm test