name: Build API Docker Image

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build API Docker image
        run: |
          docker build -t andyzetter/api:latest compose-demo-project/api